# Generated by Django 4.1.7 on 2023-03-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=64)),
                ('alpha_two_code', models.CharField(max_length=2)),
                ('web_page', models.URLField(default=None, null=True)),
            ],
        ),
    ]
